export const GET_MOMENTS = "GET_MOMENTS";
export const GET_MOMENT_BY_ID = "GET_MOMENT_BY_ID";
export const CREATE_MOMENT = "CREATE_MOMENT";
export const UPDATE_MOMENT = "UPDATE_MOMENT";
export const DELETE_MOMENT = "DELETE_MOMENT";
